# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tag.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ttag.proto\x12\x05proto\"2\n\x05param\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\".\n\x0finterface_param\x12\x1b\n\x05Param\x18\x01 \x03(\x0b\x32\x0c.proto.paramb\x06proto3')
)




_PARAM = _descriptor.Descriptor(
  name='param',
  full_name='proto.param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.param.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='proto.param.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.param.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=70,
)


_INTERFACE_PARAM = _descriptor.Descriptor(
  name='interface_param',
  full_name='proto.interface_param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Param', full_name='proto.interface_param.Param', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=118,
)

_INTERFACE_PARAM.fields_by_name['Param'].message_type = _PARAM
DESCRIPTOR.message_types_by_name['param'] = _PARAM
DESCRIPTOR.message_types_by_name['interface_param'] = _INTERFACE_PARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

param = _reflection.GeneratedProtocolMessageType('param', (_message.Message,), dict(
  DESCRIPTOR = _PARAM,
  __module__ = 'tag_pb2'
  # @@protoc_insertion_point(class_scope:proto.param)
  ))
_sym_db.RegisterMessage(param)

interface_param = _reflection.GeneratedProtocolMessageType('interface_param', (_message.Message,), dict(
  DESCRIPTOR = _INTERFACE_PARAM,
  __module__ = 'tag_pb2'
  # @@protoc_insertion_point(class_scope:proto.interface_param)
  ))
_sym_db.RegisterMessage(interface_param)


# @@protoc_insertion_point(module_scope)
